import type { AuthRequest, ClientInfo } from "@cloudflare/workers-oauth-provider";

const brandMark = `<span class="brand-mark" aria-hidden="true"><span></span><span></span></span>`;
const escapeHtml = (value: unknown): string =>
  String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");

const styles = `
:root{color-scheme:light;--background:oklch(1 0 0);--foreground:oklch(.145 0 0);--card:oklch(1 0 0);--card-foreground:oklch(.145 0 0);--primary:oklch(.205 0 0);--primary-foreground:oklch(.985 0 0);--secondary:oklch(.97 0 0);--secondary-foreground:oklch(.205 0 0);--muted:oklch(.97 0 0);--muted-foreground:oklch(.45 0 0);--accent:oklch(.97 0 0);--accent-foreground:oklch(.205 0 0);--destructive:oklch(.577 .245 27.325);--destructive-foreground:oklch(.985 0 0);--border:oklch(.922 0 0);--input:oklch(.922 0 0);--ring:oklch(.556 0 0);--radius:.625rem;--font-sans:"Geist","Inter",ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;--font-mono:"Geist Mono","SFMono-Regular",Consolas,monospace}
@media(prefers-color-scheme:dark){:root{color-scheme:dark;--background:oklch(.145 0 0);--foreground:oklch(.985 0 0);--card:oklch(.205 0 0);--card-foreground:oklch(.985 0 0);--primary:oklch(.922 0 0);--primary-foreground:oklch(.205 0 0);--secondary:oklch(.269 0 0);--secondary-foreground:oklch(.985 0 0);--muted:oklch(.269 0 0);--muted-foreground:oklch(.708 0 0);--accent:oklch(.371 0 0);--accent-foreground:oklch(.985 0 0);--destructive:oklch(.704 .191 22.216);--destructive-foreground:oklch(.985 0 0);--border:oklch(1 0 0/12%);--input:oklch(1 0 0/15%);--ring:oklch(.708 0 0)}}
*{box-sizing:border-box}html{min-width:20rem;background:var(--background)}body{min-height:100vh;margin:0;background:var(--background);color:var(--foreground);font-family:var(--font-sans);font-size:1rem;line-height:1.5;text-rendering:optimizeLegibility}button,input{font:inherit}a{color:inherit;text-underline-offset:.2em}a:hover{text-decoration-thickness:.12em}:focus-visible{outline:3px solid var(--ring);outline-offset:3px}
.skip-link{position:fixed;z-index:10;top:.75rem;left:.75rem;padding:.6rem .85rem;border-radius:var(--radius);background:var(--primary);color:var(--primary-foreground);transform:translateY(-160%);transition:transform 140ms ease}.skip-link:focus{transform:translateY(0)}.site-header,.page,.site-footer{width:min(100% - 2rem,70rem);margin-inline:auto}.site-header{height:4.75rem;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--border)}
.brand{display:inline-flex;align-items:center;gap:.7rem;font-weight:700;letter-spacing:-.025em;text-decoration:none}.brand-mark{position:relative;width:1.65rem;height:1.65rem;display:inline-grid;place-items:center}.brand-mark::before,.brand-mark::after,.brand-mark span{content:"";position:absolute;border:2px solid var(--foreground);border-radius:999px}.brand-mark::before{width:1.35rem;height:.62rem;transform:rotate(45deg)}.brand-mark::after{width:1.35rem;height:.62rem;transform:rotate(-45deg)}.brand-mark span{width:.28rem;height:.28rem;background:var(--foreground);border-width:0}.brand-mark span:first-child{left:0}.brand-mark span:last-child{right:0}.nav{display:flex;align-items:center;gap:1.25rem;color:var(--muted-foreground);font-size:.875rem}.nav a{text-decoration:none}.nav a:hover{color:var(--foreground)}
.page{padding-block:clamp(3rem,8vw,7rem)}.eyebrow{margin:0 0 1rem;color:var(--muted-foreground);font-size:.75rem;font-weight:700;letter-spacing:.12em;text-transform:uppercase}h1,h2,p{margin-top:0}h1{max-width:13ch;margin-bottom:1.25rem;font-size:clamp(2.6rem,8vw,5.8rem);line-height:.98;letter-spacing:-.065em}h2{margin-bottom:.6rem;font-size:clamp(1.35rem,3vw,1.75rem);line-height:1.2;letter-spacing:-.035em}.lede{max-width:38rem;margin-bottom:2rem;color:var(--muted-foreground);font-size:clamp(1.05rem,2.2vw,1.25rem)}
.endpoint{display:flex;align-items:center;gap:.65rem;max-width:47rem;padding:.45rem;border:1px solid var(--border);border-radius:calc(var(--radius) + .35rem);background:var(--card)}.endpoint code{min-width:0;flex:1;overflow:hidden;padding-inline:.85rem;color:var(--card-foreground);font-family:var(--font-mono);font-size:.875rem;text-overflow:ellipsis;white-space:nowrap}.button{min-height:2.75rem;display:inline-flex;align-items:center;justify-content:center;gap:.5rem;padding:.65rem 1rem;border:1px solid transparent;border-radius:var(--radius);background:var(--primary);color:var(--primary-foreground);font-weight:650;text-decoration:none;cursor:pointer;transition:opacity 120ms ease,transform 120ms ease}.button:hover{opacity:.88;text-decoration:none}.button:active{transform:translateY(1px)}.button:disabled{opacity:.58;cursor:wait}.button.secondary{border-color:var(--border);background:var(--secondary);color:var(--secondary-foreground)}
.status-line{min-height:1.5rem;margin:.65rem 0 0;color:var(--muted-foreground);font-size:.8rem}.status-dot{width:.5rem;height:.5rem;display:inline-block;margin-right:.4rem;border-radius:999px;background:var(--foreground)}.flow-section{margin-top:clamp(4rem,9vw,8rem);padding-top:2rem;border-top:1px solid var(--border)}.flow-intro{max-width:33rem;color:var(--muted-foreground)}.flow{display:grid;grid-template-columns:repeat(3,1fr);gap:0;margin:2.5rem 0 0;padding:0;list-style:none}.flow li{position:relative;padding:1.25rem 2.5rem 1.25rem 0;border-top:1px solid var(--foreground)}.flow li:not(:last-child)::after{content:"→";position:absolute;top:1.1rem;right:1rem;color:var(--muted-foreground)}.flow strong,.flow span{display:block}.flow span{margin-top:.3rem;color:var(--muted-foreground);font-size:.875rem}.site-footer{min-height:5rem;display:flex;align-items:center;justify-content:space-between;gap:1rem;border-top:1px solid var(--border);color:var(--muted-foreground);font-size:.8rem}.site-footer p{margin:0}
.consent-page{width:min(100% - 2rem,34rem);padding-block:clamp(2.5rem,8vw,5rem)}.consent-card{padding:clamp(1.35rem,5vw,2.25rem);border:1px solid var(--border);border-radius:calc(var(--radius) + .5rem);background:var(--card);color:var(--card-foreground)}.client-identity{display:flex;align-items:center;gap:.85rem;margin-bottom:1.75rem}.client-avatar{width:2.75rem;height:2.75rem;display:grid;flex:0 0 auto;place-items:center;border-radius:var(--radius);background:var(--primary);color:var(--primary-foreground);font-weight:750}.client-identity strong,.client-identity span{display:block}.client-identity span{color:var(--muted-foreground);font-size:.82rem}.consent-card h1{max-width:none;margin-bottom:.75rem;font-size:clamp(1.8rem,6vw,2.5rem);line-height:1.08;letter-spacing:-.045em}.consent-copy{color:var(--muted-foreground)}
.permissions{margin:1.75rem 0;padding:1.25rem 0;border-block:1px solid var(--border)}.permissions h2{font-size:.8rem;letter-spacing:.08em;text-transform:uppercase}.permission{display:grid;grid-template-columns:1.5rem 1fr;gap:.65rem;margin-top:1rem}.permission-mark{width:1.3rem;height:1.3rem;display:grid;place-items:center;margin-top:.1rem;border:1px solid var(--border);border-radius:999px;font-size:.72rem;font-weight:800}.permission strong,.permission span{display:block}.permission span{margin-top:.15rem;color:var(--muted-foreground);font-size:.85rem}.request-details{margin:0 0 1.5rem}.request-details div{display:grid;grid-template-columns:6rem minmax(0,1fr);gap:.75rem;padding-block:.45rem}.request-details dt{color:var(--muted-foreground);font-size:.8rem}.request-details dd{min-width:0;margin:0;overflow-wrap:anywhere;font-family:var(--font-mono);font-size:.78rem}.form-actions{display:grid;grid-template-columns:1fr auto;gap:.65rem}.form-actions .button{width:100%}.trust-note{margin:1rem 0 0;color:var(--muted-foreground);font-size:.76rem;text-align:center}.error-symbol{width:3rem;height:3rem;display:grid;place-items:center;margin-bottom:1.25rem;border-radius:999px;background:var(--destructive);color:var(--destructive-foreground);font-size:1.3rem;font-weight:800}
@media(max-width:43rem){.nav a:first-child{display:none}.endpoint{align-items:stretch;flex-direction:column;padding:.65rem}.endpoint code{padding:.45rem;white-space:normal;overflow-wrap:anywhere}.flow{grid-template-columns:1fr}.flow li{padding-right:0}.flow li:not(:last-child)::after{content:"↓";top:auto;right:.25rem;bottom:-.85rem;padding:0 .35rem;background:var(--background)}.site-footer{align-items:flex-start;flex-direction:column;justify-content:center}.form-actions{grid-template-columns:1fr}.form-actions .secondary{order:2}}@media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;transition-duration:.01ms!important}}
`;

function page(title: string, description: string, content: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><meta name="color-scheme" content="light dark"/><meta name="theme-color" content="#ffffff" media="(prefers-color-scheme: light)"/><meta name="theme-color" content="#0a0a0a" media="(prefers-color-scheme: dark)"/><meta name="description" content="${escapeHtml(description)}"/><title>${escapeHtml(title)} · ERPipe</title><style>${styles}</style></head><body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/" aria-label="ERPipe home">${brandMark}<span>ERPipe</span></a><nav class="nav" aria-label="Primary navigation"><a href="https://github.com/erpipe-org/erpipe">Documentation</a><a href="/health">System health</a></nav></header>${content}<footer class="site-footer"><p>ERPipe self-host · Open-source MCP for Odoo</p><p>OAuth 2.1 · PKCE S256</p></footer></body></html>`;
}

export function renderHomePage(input: { endpoint: string; slug: string }): string {
  const endpoint = escapeHtml(input.endpoint);
  const slug = escapeHtml(input.slug);
  const content = `<main class="page" id="main"><section aria-labelledby="hero-title"><p class="eyebrow">Self-hosted MCP gateway</p><h1 id="hero-title">Your Odoo data, ready for AI.</h1><p class="lede">ERPipe gives MCP-compatible clients a secure, direct route to the Odoo connection you control.</p><div class="endpoint" aria-label="MCP connection endpoint"><code id="endpoint-value">${endpoint}</code><button class="button" id="copy-endpoint" type="button">Copy endpoint</button></div><p class="status-line" id="copy-status" aria-live="polite"><span class="status-dot" aria-hidden="true"></span>Instance online · connection <code>${slug}</code></p></section><section class="flow-section" aria-labelledby="flow-title"><p class="eyebrow">Connection path</p><h2 id="flow-title">One endpoint. No extra control plane.</h2><p class="flow-intro">Credentials stay in your Worker environment while ERPipe translates MCP requests into Odoo operations.</p><ol class="flow"><li><strong>AI client</strong><span>Connect with the endpoint above</span></li><li><strong>ERPipe</strong><span>Authorize and route MCP tools</span></li><li><strong>Odoo</strong><span>Execute with your configured access</span></li></ol></section></main><script>const copyButton=document.getElementById("copy-endpoint");const status=document.getElementById("copy-status");copyButton?.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(document.getElementById("endpoint-value")?.textContent??"");copyButton.textContent="Copied";status.textContent="Endpoint copied to clipboard.";window.setTimeout(()=>{copyButton.textContent="Copy endpoint"},1800)}catch{status.textContent="Copy failed. Select the endpoint and copy it manually."}});</script>`;
  return page(
    "Self-host gateway",
    "Connect MCP-compatible AI clients to Odoo through your self-hosted ERPipe gateway.",
    content,
  );
}

export function renderAuthorizePage(input: {
  slug: string;
  oauthState: string;
  request: AuthRequest;
  client: ClientInfo | null;
}): string {
  const clientName = input.client?.clientName?.trim() || "An MCP client";
  const initial = escapeHtml(clientName.slice(0, 1).toUpperCase());
  const scope = input.request.scope.length
    ? input.request.scope.join(", ")
    : "Default ERPipe access";
  const resource = Array.isArray(input.request.resource)
    ? input.request.resource.join(", ")
    : input.request.resource || `/${input.slug}/mcp`;
  const content = `<main class="page consent-page" id="main"><section class="consent-card" aria-labelledby="consent-title"><div class="client-identity"><span class="client-avatar" aria-hidden="true">${initial}</span><div><strong>${escapeHtml(clientName)}</strong><span>OAuth client requesting access</span></div></div><h1 id="consent-title">Connect to this ERPipe instance?</h1><p class="consent-copy">Only continue if you started this request and trust the client shown above.</p><div class="permissions"><h2>This will allow the client to</h2><div class="permission"><span class="permission-mark" aria-hidden="true">✓</span><div><strong>Use ERPipe MCP tools</strong><span>Access the tools and prompts exposed by this server.</span></div></div><div class="permission"><span class="permission-mark" aria-hidden="true">✓</span><div><strong>Act through your Odoo connection</strong><span>Operations run with the credentials configured by the instance operator.</span></div></div></div><dl class="request-details"><div><dt>Connection</dt><dd>${escapeHtml(input.slug)}</dd></div><div><dt>Resource</dt><dd>${escapeHtml(resource)}</dd></div><div><dt>Scope</dt><dd>${escapeHtml(scope)}</dd></div><div><dt>Client ID</dt><dd>${escapeHtml(input.request.clientId)}</dd></div></dl><form id="authorize-form" method="POST" action="/authorize"><input type="hidden" name="oauth_state" value="${escapeHtml(input.oauthState)}"/><input type="hidden" name="email" value="selfhost@local"/><div class="form-actions"><button class="button" id="approve-button" type="submit">Allow connection</button><a class="button secondary" href="/">Cancel</a></div></form><p class="trust-note">ERPipe never asks this client for your Odoo password.</p></section></main><script>document.getElementById("authorize-form")?.addEventListener("submit",()=>{const button=document.getElementById("approve-button");if(button instanceof HTMLButtonElement){button.disabled=true;button.textContent="Connecting…"}});</script>`;
  return page("Authorize connection", `Review access requested by ${clientName}.`, content);
}

export function renderErrorPage(title: string, message: string): string {
  const content = `<main class="page consent-page" id="main"><section class="consent-card" role="alert" aria-labelledby="error-title"><div class="error-symbol" aria-hidden="true">!</div><p class="eyebrow">Request could not continue</p><h1 id="error-title">${escapeHtml(title)}</h1><p class="consent-copy">${escapeHtml(message)}</p><a class="button" href="/">Return to ERPipe</a></section></main>`;
  return page(title, message, content);
}
